### ISSUE TITLE
Needs triggers on each block in order to meet needs of compound dapp

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/compound-subgraph#1]
The compound dapp right now hits infura every block in order to get the infura ethereum node to run `view` functions that calculate the interest a user has earned, without actually updating any contract state. It is a way to get free updates, and works quite well.

However, the one problem I see is that the compound dapp only does this when you have their dapp open, so at any moment maybe 100 people have the dapp open, which means infura is taking 100 queries every block, which is reasonable. 

But how would we get the subgraph to do such a thing? The only way I see the subgraph working right now would be that it updates **every** account that has interacted with compound each block. Which would be a ton of queries, and a ton of state updates each block. 

Maybe i am missing something here, but this does not seem like an easy fix! Would love some others input.

This is related to this issue https://github.com/graphprotocol/graph-node/issues/788 for having block triggers

**Comment by davekay100** [comment]
talking to robert, compound subgraph doesnt need block triggers. I agree with this
